"""Export frames to PDF with customizable layout."""

from __future__ import annotations

import base64
import io
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np
from PIL import Image

from aive.imaging import bgr_to_jpeg_base64


@dataclass
class PdfLayoutSettings:
    page_size: str = "A4"  # A4, Letter, Legal, A3
    orientation: str = "portrait"  # portrait | landscape
    columns: int = 2
    rows: int = 3
    margin_mm: float = 12.0
    title: str = "AI-IVE Frame Export"
    show_frame_labels: bool = True
    show_timestamp: bool = True
    footer_text: str = "Generated by AI-IVE"


PAGE_SIZES_MM = {
    "A4": (210, 297),
    "Letter": (216, 279),
    "Legal": (216, 356),
    "A3": (297, 420),
}


def export_frames_to_pdf(
    frames: list[np.ndarray],
    output_path: Path,
    layout: PdfLayoutSettings | None = None,
    labels: list[str] | None = None,
) -> dict[str, Any]:
    layout = layout or PdfLayoutSettings()
    try:
        from reportlab.lib.pagesizes import A3, A4, landscape, letter, legal, portrait
        from reportlab.lib.units import mm
        from reportlab.pdfgen import canvas
    except ImportError:
        return _export_pdf_pillow_fallback(frames, output_path, layout, labels)

    size_map = {"A4": A4, "Letter": letter, "Legal": legal, "A3": A3}
    page = size_map.get(layout.page_size, A4)
    if layout.orientation == "landscape":
        page = landscape(page)

    c = canvas.Canvas(str(output_path), pagesize=page)
    pw, ph = page
    margin = layout.margin_mm * mm
    cols = max(1, layout.columns)
    rows = max(1, layout.rows)
    per_page = cols * rows
    cell_w = (pw - 2 * margin) / cols
    cell_h = (ph - 2 * margin - 40) / rows

    c.setFont("Helvetica-Bold", 14)
    c.drawString(margin, ph - margin - 14, layout.title)

    idx = 0
    page_num = 1
    while idx < len(frames):
        if idx > 0 and idx % per_page == 0:
            c.showPage()
            page_num += 1
            c.setFont("Helvetica-Bold", 14)
            c.drawString(margin, ph - margin - 14, f"{layout.title} (p.{page_num})")

        slot = idx % per_page
        col = slot % cols
        row = slot // cols
        x = margin + col * cell_w
        y = ph - margin - 30 - (row + 1) * cell_h

        frame = frames[idx]
        jpeg_b64 = bgr_to_jpeg_base64(frame, quality=80)
        img_data = base64.b64decode(jpeg_b64)
        img = Image.open(io.BytesIO(img_data))
        iw, ih = img.size
        scale = min((cell_w - 8) / iw, (cell_h - 20) / ih)
        dw, dh = iw * scale, ih * scale
        buf = io.BytesIO()
        img.resize((int(dw), int(dh)), Image.Resampling.LANCZOS).save(buf, format="JPEG")
        buf.seek(0)
        from reportlab.lib.utils import ImageReader

        c.drawImage(ImageReader(buf), x + 4, y + 12, width=dw, height=dh)

        if layout.show_frame_labels:
            label = (labels[idx] if labels and idx < len(labels) else f"Frame {idx + 1}")
            c.setFont("Helvetica", 8)
            c.drawString(x + 4, y + 4, label)

        idx += 1

    if layout.footer_text:
        c.setFont("Helvetica", 7)
        c.drawString(margin, margin / 2, layout.footer_text)

    c.save()
    return {"success": True, "output": str(output_path), "frame_count": len(frames)}


def _export_pdf_pillow_fallback(
    frames: list[np.ndarray],
    output_path: Path,
    layout: PdfLayoutSettings,
    labels: list[str] | None,
) -> dict[str, Any]:
    images = []
    for i, f in enumerate(frames):
        rgb = f[:, :, ::-1]
        images.append(Image.fromarray(rgb.astype(np.uint8)))
    if not images:
        return {"success": False, "error": "No frames"}
    images[0].save(
        output_path.with_suffix(".pdf"),
        save_all=True,
        append_images=images[1:],
        resolution=100.0,
    )
    return {"success": True, "output": str(output_path.with_suffix(".pdf")), "frame_count": len(frames), "note": "basic_pdf"}
