#!/usr/bin/env python3
"""Generate short A/V test files for R-115 / R-117 (mux + auto pad).

Output: ~/Desktop/chakshu-test-data/
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

OUT = Path.home() / "Desktop" / "chakshu-test-data"


def ffmpeg_exe() -> str:
    from aive.codecs.ffmpeg_bin import require_ffmpeg

    return require_ffmpeg()


def run(cmd: list[str]) -> None:
    print(" ", " ".join(cmd))
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0:
        raise RuntimeError(r.stderr[-800:] or "ffmpeg failed")


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    ff = ffmpeg_exe()
    print(f"Using FFmpeg: {ff}")
    print(f"Output dir:   {OUT}\n")

    video = OUT / "dummy-17s-video.mp4"
    audio_long = OUT / "dummy-30s-commentary.aac"
    audio_short = OUT / "dummy-10s-commentary.aac"
    expected_padded = OUT / "expected-padded-30s.mp4"

    print("[1/4] 17s test video (640x360, tone + color bars label)...")
    run(
        [
            ff,
            "-y",
            "-f",
            "lavfi",
            "-i",
            "testsrc=size=640x360:rate=25:duration=17",
            "-f",
            "lavfi",
            "-i",
            "sine=frequency=440:sample_rate=48000:duration=17",
            "-c:v",
            "libx264",
            "-pix_fmt",
            "yuv420p",
            "-c:a",
            "aac",
            "-shortest",
            str(video),
        ]
    )

    print("[2/4] 30s external audio (longer — triggers R-117 auto pad)...")
    run(
        [
            ff,
            "-y",
            "-f",
            "lavfi",
            "-i",
            "sine=frequency=880:sample_rate=48000:duration=30",
            "-c:a",
            "aac",
            str(audio_long),
        ]
    )

    print("[3/4] 10s external audio (shorter — trim / shortest test)...")
    run(
        [
            ff,
            "-y",
            "-f",
            "lavfi",
            "-i",
            "sine=frequency=220:sample_rate=48000:duration=10",
            "-c:a",
            "aac",
            str(audio_short),
        ]
    )

    print("[4/4] Reference padded output (17s video + 30s audio, manual pad)...")
    run(
        [
            ff,
            "-y",
            "-i",
            str(video),
            "-i",
            str(audio_long),
            "-filter_complex",
            "[0:v]tpad=stop_mode=clone:stop_duration=13[v]",
            "-map",
            "[v]",
            "-map",
            "0:a?",
            "-map",
            "1:a:0",
            "-c:v",
            "libx264",
            "-preset",
            "fast",
            "-crf",
            "18",
            "-pix_fmt",
            "yuv420p",
            "-c:a:0",
            "copy",
            "-c:a:1",
            "aac",
            str(expected_padded),
        ]
    )

    manifest = OUT / "TEST-AV-MUX.md"
    manifest.write_text(
        f"""# A/V mux & padding test data (R-115 / R-117)

Generated by `scripts/generate-av-test-data.py`.

## Files

| File | Duration | Purpose |
|------|----------|---------|
| `{video.name}` | ~17s | Base video with embedded 440Hz tone |
| `{audio_long.name}` | ~30s | Longer audio — **auto pad** (+13s frozen last frame) |
| `{audio_short.name}` | ~10s | Shorter audio — **trim to shortest** test |
| `{expected_padded.name}` | ~30s | Reference output (manual FFmpeg pad) |
| `dummy-17s.srt` | — | Subtitle file aligned to 17s video |

## UI test — Add Audio Stream (R-115 + R-117)

1. Load paths in **Forensic Tools** → **Add Audio Stream**:
   - **Video:** `{video}`
   - **External audio:** `{audio_long}`
   - **Output:** `~/Desktop/chakshu-export/video-padded-test.mp4`
2. Leave **Automatically pad video** checked.
3. Duration compare should show **+13s** pad hint.
4. **Add audio to video** → output ~30s, 2 audio tracks (original + commentary).

## API test

```bash
# Duration compare
curl -s "http://127.0.0.1:9450/api/capabilities/audio/duration-compare?video_path={video}&audio_path={audio_long}"

# Auto pad mux
curl -s -X POST http://127.0.0.1:9450/api/capabilities/audio/mux \\
  -H "Content-Type: application/json" \\
  -d '{{"video_path":"{video}","audio_path":"{audio_long}","output_path":"~/Desktop/chakshu-export/api-pad-test.mp4","mode":"add","auto_pad_video":true}}'
```

## Shorter audio test (trim)

Use `{audio_short}` with **Trim to shortest when video is longer** checked.
""",
        encoding="utf-8",
    )

    print(f"\nDone. See {manifest}")
    for p in (video, audio_long, audio_short, expected_padded, manifest):
        print(f"  {p}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
